name: Preflight

permissions:
  contents: read
  issues: write

on:
  push:
    branches: [ main ]

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify required secrets
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          for var in DROPLET_HOST DROPLET_USER DROPLET_SSH_KEY OPENAI_API_KEY AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY SLACK_WEBHOOK_URL; do
            if [ -z "${!var}" ]; then
              echo "::error::Missing required secret $var"
              exit 1
            fi
          done

