name: On-Demand Refactor

permissions:
  contents: write
  issues: write

on:
  issue_comment:
    types:
      - created
  pull_request_review_comment:
    types:
      - created

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  refactor:
    if: ${{ (github.event.issue.pull_request || github.event.pull_request) && contains(github.event.comment.body, '/refactor') }}
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Checkout PR
        run: gh pr checkout $PR_NUMBER
      - name: Run Codex Refactor
        run: python scripts/codex_refactor.py --diff "$(git diff origin/main)"
      - name: Commit refactored code
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions[bot]"
          author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          message: "Apply AI refactor suggestions"
          add: "refactor-suggestions/*.py"
      - name: Create Refactor PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "AI-driven refactor for issue #${{ env.PR_NUMBER }}"
          commit-message: "Apply AI refactors"
          base: main
          branch: refactor/${{ env.PR_NUMBER }}
          body: |
            This PR applies function-level refactor suggestions from ChatGPT to address issues uncovered in the nightly health check.
