name: Release

permissions:
  contents: read
  issues: write

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Install build deps
        run: |
          pip install --upgrade pip
          pip install build
      - name: Build wheel
        run: python -m build --wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}

