name: Draft Release Notes
permissions:
  contents: read
  issues: write

on:
  release:
    types:
      - published

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  draft-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Generate release notes
        id: gen
        run: |
          notes=$(python scripts/generate_release_notes.py)
          echo "notes<<EOF" >> "$GITHUB_OUTPUT"
          echo "$notes" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ github.event.release.tag_name }}" \
            --notes "${{ steps.gen.outputs.notes }}"
