repos:
  - repo: local
    hooks:
      - id: repo-guard
        name: repo-guard
        entry: tools/ci/guard.sh
        language: system
        pass_filenames: false
      - id: forbid-legacy-trade-execution-import
        name: Forbid 'trade_execution' imports
        entry: bash -c "! grep -rn \"^(from|import)\\s\\+trade_execution\\b\" --include=\"*.py\" ."
        language: system
        pass_filenames: false
        description: Prevents legacy trade_execution imports; use 'from ai_trading import ExecutionEngine' instead
      - id: check-no-legacy-symbols
        name: check-no-legacy-symbols
        entry: python tools/check_no_legacy_symbols.py
        language: system
        pass_filenames: false

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: \.secrets\.baseline$
        stages: [manual]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.12

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: [--config-file=mypy.ini]
