target-version = "py311"

# AI-AGENT-REF: broaden lint rules and safe defaults
[lint]
select = [
  "E9","F63","F7","F82","BLE001","DTZ005",  # existing high-signal
  "F401","F841","E711","E402","F632"        # mechanical reductions
]
dummy-variable-rgx = "^(_+|unused_|ignored_|ignore_).*$"

[lint.per-file-ignores]
# Re-exports and namespace packages are allowed to have seemingly unused imports.
"**/__init__.py" = ["F401"]
# Tests can intentionally compare to None/True/False or keep throwaway vars.
"tests/**" = ["E711","F841"]

[lint.pycodestyle]
max-line-length = 120

[lint.flake8-unused-arguments]
ignore-variadic-names = true

[lint.isort]
known-first-party = ["ai_trading","trade_execution"]

[lint.pep8-naming]
classmethod-decorators = ["classmethod"]

