[project]
name = "ai-trading-bot"
version = "0.1.0"
description = "AI trading bot"
requires-python = "==3.12.3"

[project.scripts]
ai-trading-bot = "ai_trading.main:main"

[project.optional-dependencies]
dev = [
  "pytest",
  "flake8",
  "black",
  "mkdocs",
]
test = [
  "pytest",
]
