[project]
name = "ai-trading-bot"
version = "0.0.0"
description = "AI trading bot (lightweight testable build)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas>=1.5",
  "requests>=2.31",
]

[project.optional-dependencies]
ml = ["scikit-learn>=1.3"]
test = ["pytest>=7.4", "pytest-cov>=4.1"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ai_trading*", "trade_execution*"]
exclude = ["tests*", "scripts*", "artifacts*"]

[tool.black]
line-length = 120
target-version = ["py311"]


[tool.ruff]
target-version = "py311"
line-length = 100
src = ["ai_trading", "trade_execution", "tests", "tools"]
extend-exclude = ["**/.venv", "**/venv", "build", "dist", "notebooks", "artifacts", "tools/static_import_rewrites.txt"]

# Focus on safe mechanical families only.
[tool.ruff.lint]
select = ["E", "F", "UP", "DTZ", "T201"]  # AI-AGENT-REF: safe lint families
ignore = ["E501"]

# Allow prints in tests/tools; allow re-export F401 in package __init__ files.
[tool.ruff.lint.per-file-ignores]
"tests/**" = ["T201"]
"tools/**" = ["T201", "E402"]
"scripts/**" = ["T201", "E402"]
"**/__init__.py" = ["F401"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
  "tests"
]
markers = [
  "integration: tests that require network or vendor APIs",
  "slow: tests that are slow or long-running"
]
filterwarnings = [
  "ignore::DeprecationWarning",
]
