[project]
name = "ai-trading-bot"
version = "0.1.0"
description = "AI trading bot"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pydantic>=2.6,<3",
    "pydantic-settings>=2.2,<3", 
    "requests>=2.31,<3",
    "numpy>=1.24,<3.0",
    "pandas>=2",
    "scikit-learn>=1.4.2",
    "pandas_market_calendars>=4.3",
    "tenacity==8.2.2",
    "ratelimit==2.2.1",
    "ta==0.11.0",
    "joblib>=1.3",
    "python-dotenv>=1.0",
    "prometheus-client==0.17.1",
    "tzlocal==4.3",
    "pyarrow>=12.0.0",
    "pandas_ta==0.3.14b0",
    "beautifulsoup4>=4.11.1",
    "flask>=2.3.0",
    "schedule>=1.1.0",
    "portalocker==2.7.0",
    "alpaca-py>=0.42.0",
    "alpaca-trade-api>=3.1.0",
    "hmmlearn>=0.3.0",
    "finnhub-python>=2.4.0",
    "lightgbm>=4.2.1",
    "pybreaker==1.0.0",
    "pytz>=2024.1",
    "yfinance>=0.2.28",
    "websockets>=10.4,<11",
    "urllib3>=1.26,<3.0",
    "statsmodels>=0.14.1,<0.15",
    "transformers==4.35.2",
    "python-dateutil>=2.9.0",
    "optuna==3.6.1",
    "stable-baselines3==2.3.2",
    "gymnasium==0.29.1",
    "psutil>=5.9.8",
    "filelock>=3.13.1",
    "xgboost>=1.7.6",
    "lxml",
    "sqlalchemy>=2.0.0",
    "alembic>=1.12.0",
    "psycopg2-binary>=2.9.0",
    "redis>=4.6.0",
    "celery>=5.3.0",
    "typing-extensions>=4.0.0",
    "dataclasses-json>=0.5.7",
    "cachetools>=5.0.0",
    "cryptography>=3.4.8",
    "PyYAML==6.0.1",
    "Cython>=0.29.36",
]

[tool.setuptools]
packages = ["ai_trading"]

[project.scripts]
ai-trade = "ai_trading.__main__:run_trade"
ai-backtest = "ai_trading.__main__:run_backtest"
ai-health = "ai_trading.__main__:run_healthcheck"

[project.optional-dependencies]
dev = [
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0", 
  "pytest-xdist>=3.0.0",
  "pytest-benchmark>=4.0.0",
  "pytest-asyncio>=0.20.2",
  "flake8>=6.0.0",
  "mypy>=1.0.0",
  "black>=23.0.0",
  "hypothesis>=6.0.0",
  "coverage>=7.0.0",
]
test = [
  "pytest>=7.0.0",
  "pytest-cov>=4.0.0",
  "pytest-xdist>=3.0.0", 
  "pytest-benchmark>=4.0.0",
  "pytest-asyncio>=0.20.2",
  "hypothesis>=6.0.0",
]

[tool.ruff]
select = ["E", "F", "W", "B", "I", "T201", "E722"]
ignore = []
exclude = ["tests/**/*.py"]  # Allow print in tests
