[project]
name = "ai-trading-bot"
version = "0.0.0"
description = "AI trading bot (lightweight testable build)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas>=1.5",
  "requests>=2.31",
]

[project.optional-dependencies]
ml = ["scikit-learn>=1.3"]
test = ["pytest>=7.4", "pytest-cov>=4.1"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ["py311"]


[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["artifacts", "dist", "build", ".venv", ".tox"]

[tool.ruff.lint]
# Safe, mechanical buckets only
select = ["E", "F", "I", "UP", "DTZ", "T201", "BLE", "PL"]
ignore = ["E501"]  # keep line-length ignored repo-wide

[tool.ruff.lint.per-file-ignores]
"ai_trading/**/__init__.py" = ["F401"]
"trade_execution/**/__init__.py" = ["F401"]
"ai_trading/**/reexports.py" = ["F401"]
"ai_trading/scripts/**" = ["T201"]
