[project]
name = "ai-trading-bot"
version = "0.0.0"
description = "AI trading bot (lightweight testable build)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas>=1.5",
  "requests>=2.31",
]

[project.optional-dependencies]
ml = ["scikit-learn>=1.3"]
test = ["pytest>=7.4", "pytest-cov>=4.1"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 100


[tool.ruff]
target-version = "py311"
line-length = 100
extend-exclude = ["artifacts", "build", "dist", ".venv", "venv", ".tox", ".mypy_cache"]

# Prefer high-signal, safe-to-fix rules:
select = [
  "E",
  "W",
  "F401",
  "F541",
  "I",
  "RUF100",
]

# Keep risky transforms (e.g., SIM/UP/PL) disabled for this pass.
ignore = [
  "E402",
  "F403",
  "F405",
  "F821",
]

# Treat common “intentionally unused” names as OK.
dummy-variable-rgx = "^(_|unused_|ignore_|ignored_|_unused|_ignored|dummy|.*_unused)$"
fix = true

[tool.ruff.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]
"tests/**" = ["E402"]
"tools/**" = ["E402"]
