[project]
name = "ai-trading-bot"
version = "0.0.0"
description = "AI trading bot (lightweight testable build)"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pandas>=1.5",
  "requests>=2.31",
]

[project.optional-dependencies]
ml = ["scikit-learn>=1.3"]
test = ["pytest>=7.4", "pytest-cov>=4.1"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 120
target-version = ["py311"]


[tool.ruff]
target-version = "py311"
src = ["ai_trading", "trade_execution", "tests", "tools"]
extend-exclude = ["**/.venv", "**/venv", "build", "dist", "notebooks", "artifacts"]

# Focus on safe mechanical families only.
[tool.ruff.lint]
select = [
  "E",   # pycodestyle (excluding E501 via ignore)
  "F",   # pyflakes
  "I",   # import order
  "UP",  # pyupgrade (safe modernizations)
  "BLE", # blind exception
  "DTZ", # timezone-naive datetime
  "T20", # print statements
  "PL",  # pylint-inspired (we’ll manage risk via ignores below)
]

# Global risk trims
ignore = [
  "E501",    # line length
  "PLR0913", # too-many-args (noise for strategies)
  "PLR0912", # too-many-branches
  "PLR0915", # too-many-statements
]

# Allow prints in tests/tools; allow re-export F401 in package __init__ files.
[tool.ruff.lint.per-file-ignores]
"tests/**/*" = ["T201", "F401", "F841", "PLR2004", "E402", "F821", "BLE001", "DTZ011"]
"tools/**/*" = ["T201", "E701", "BLE001"]
"scripts/**/*" = ["E402", "PLR2004"]
"**/__init__.py" = ["F401", "F403"]
