"""
Trading constants for institutional-grade trading platform.

Contains configuration constants, market parameters, and system limits
used throughout the trading platform.
"""
from datetime import time
from typing import Any
MARKET_HOURS = {'PRE_MARKET_START': time(9, 0), 'MARKET_OPEN': time(14, 30), 'MARKET_CLOSE': time(21, 0), 'AFTER_HOURS_END': time(1, 0)}
RISK_PARAMETERS = {'MAX_PORTFOLIO_RISK': 0.025, 'MAX_CORRELATION_EXPOSURE': 0.15, 'MAX_SECTOR_CONCENTRATION': 0.15, 'MIN_LIQUIDITY_THRESHOLD': 1000000, 'MAX_POSITION_SIZE': 0.25, 'STOP_LOSS_MULTIPLIER': 1.8, 'TAKE_PROFIT_MULTIPLIER': 2.5}
KELLY_PARAMETERS = {
    'MIN_SAMPLE_SIZE': 20,
    'MAX_KELLY_FRACTION': 0.15,
    'CONFIDENCE_LEVEL': 0.9,
    'LOOKBACK_PERIODS': 252,
    'REBALANCE_FREQUENCY': 21,
}
EXECUTION_PARAMETERS = {'MAX_SLIPPAGE_BPS': 15, 'PARTICIPATION_RATE': 0.15, 'MIN_ORDER_SIZE': 100, 'MAX_ORDER_SIZE': 10000, 'ORDER_TIMEOUT_SECONDS': 180, 'RETRY_ATTEMPTS': 3, 'CANCEL_THRESHOLD_SECONDS': 60}
DATA_PARAMETERS = {'MAX_DATA_AGE_MINUTES': 5, 'HEALTH_CHECK_INTERVAL': 60, 'LOG_ROTATION_DAYS': 30, 'METRICS_RETENTION_DAYS': 365, 'BACKUP_FREQUENCY_HOURS': 6}
DATABASE_PARAMETERS = {'CONNECTION_POOL_SIZE': 20, 'MAX_OVERFLOW': 10, 'POOL_TIMEOUT_SECONDS': 30, 'POOL_RECYCLE_SECONDS': 3600, 'QUERY_TIMEOUT_SECONDS': 30}
PERFORMANCE_THRESHOLDS = {'MIN_SHARPE_RATIO': 1.2, 'MAX_DRAWDOWN': 0.15, 'MIN_WIN_RATE': 0.48, 'MIN_PROFIT_FACTOR': 1.2, 'MAX_VAR_95': 0.05}
SYSTEM_LIMITS = {'MAX_CONCURRENT_ORDERS': 100, 'MAX_DAILY_TRADES': 1000, 'MAX_SYMBOLS_TRACKED': 500, 'MAX_MEMORY_USAGE_GB': 8, 'MAX_CPU_USAGE_PERCENT': 80}
TRADING_CONSTANTS: dict[str, Any] = {
    'MARKET_HOURS': MARKET_HOURS,
    'RISK_PARAMETERS': RISK_PARAMETERS,
    'KELLY_PARAMETERS': KELLY_PARAMETERS,
    'EXECUTION_PARAMETERS': EXECUTION_PARAMETERS,
    'DATA_PARAMETERS': DATA_PARAMETERS,
    'DATABASE_PARAMETERS': DATABASE_PARAMETERS,
    'PERFORMANCE_THRESHOLDS': PERFORMANCE_THRESHOLDS,
    'SYSTEM_LIMITS': SYSTEM_LIMITS,
}
