# Composite action to send Slack messages
name: Slack Notify
inputs:
  text:
    description: Message text
    required: true
  webhook_url:
    description: Slack webhook URL
    required: true
runs:
  using: composite
  steps:
    - uses: slackapi/slack-github-action@v2
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
      with:
        payload: |
          {
            "text": ${{ toJSON(inputs.text) }}
          }

