name: Daily Backup
permissions:
  contents: read
on:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install AWS CLI
        run: python -m pip install awscli --upgrade
      - name: Sync models to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync ./models s3://my-bucket/models --delete
      - name: Backup data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          tar czf backup-$(date +%F).tar.gz ./data
          aws s3 cp backup-$(date +%F).tar.gz s3://my-bucket/backups/
