name: Daily Backup
on:
  schedule:
    - cron: '0 3 * * *'  # 3 AM UTC daily

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CLI
        run: pip install awscli --upgrade
      - name: Sync models to S3
        run: aws s3 sync ./models s3://my-bucket/models --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
