# CI workflow running lint, type checks and tests.
# Triggers on push and pull_request events.
# Required secrets: none
name: CI and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.10.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi
          pip install pytest-cov

      - name: Lint and format check
        run: |
          pip install flake8 black
          flake8 \
            --max-line-length=160 \
            --extend-ignore=E302,E305,E402,E203,E501,F811 \
            --statistics \
            --exclude scripts/ .
          black --check .

      - name: Type check
        run: |
          pip install mypy
          mypy .

      - name: Pytest
        run: pytest --maxfail=1 --disable-warnings --junitxml=reports/junit.xml --cov=. --cov-report=xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

