name: CI and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pytest-cov

      - name: Lint & Type-Check
        run: |
          pip install flake8 mypy
          flake8 \
            --max-line-length=160 \
            --extend-ignore=E302,E305,E402,E203,E501,F811 \
            --statistics .
          mypy .

      - name: Pytest
        run: pytest --maxfail=1 --disable-warnings --junitxml=reports/junit.xml --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
