name: Coverage

permissions:
  contents: read
  issues: write

on:
  push:
  pull_request:

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage[toml] codecov pytest-cov
      - name: Run tests with coverage
        run: python -m pytest --cov=.
      - name: Upload coverage
        uses: codecov/codecov-action@v5

