name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy and restart
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'ENDSSH'
          set -e
          cd /home/aiuser/ai-trading-bot
          PREV_COMMIT=$(git rev-parse HEAD)
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          # Install dev dependencies if requirements-dev.txt exists
          [ -f requirements-dev.txt ] && pip install -r requirements-dev.txt || echo "No dev requirements file found"
          if ! sudo systemctl restart ai-trading-scheduler.service; then
            echo "Restart failed, rolling back" >&2
            git reset --hard "$PREV_COMMIT"
            sudo systemctl restart ai-trading-scheduler.service
          fi
        ENDSSH
