name: Publish Docs

permissions:
  contents: read
  issues: write
on:
  push:
    branches: [ main ]

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true
jobs:
  deploy-docs:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install MkDocs
        run: pip install mkdocs mkdocs-material
      - name: Deploy docs to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force --clean
