name: Nightly Health Check
on:
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC daily
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: SSH & run tests
        if: ${{ secrets.DROPLET_HOST != '' }}
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~/ai-trading-bot
            systemctl is-active --quiet ai-trading-scheduler
            source venv/bin/activate
            pytest --maxfail=1 --disable-warnings -q

