name: Nightly Health Check
on:
  schedule:
    - cron: '0 1 * * *'  # 1 AM UTC daily
jobs:
  health-check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Deploy to DigitalOcean Droplet
        if: ${{ secrets.DROPLET_HOST != '' }}
        uses: appleboy/ssh-action@v0.1.7
        with:
          host:     ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key:      ${{ secrets.DROPLET_SSH_KEY }}
          port:     22
          known_hosts: '*'
          script: |
            python3 -m venv ~/venv
            source ~/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            ./deploy.sh

