name: Nightly Health Check
permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: ./deploy.sh
