name: Issue Triage

permissions:
  contents: read
  issues: write

on:
  issues:
    types: [ opened ]

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh
      - name: Determine labels
        id: triage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          labels=$(python scripts/triage_issue.py \
            --title "${{ github.event.issue.title }}" \
            --body "${{ github.event.issue.body }}")
          echo "labels=$labels" >> "$GITHUB_OUTPUT"
      - name: Apply Labels
        if: steps.triage.outputs.labels != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-label "${{ steps.triage.outputs.labels }}"
