name: Model Performance Monitor

permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true
jobs:
  monitor:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run backtest & record metrics
        run: |
          python scripts/backtest.py --output metrics.json --plot metrics.png
      - name: Commit metrics
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update performance metrics"
      - name: Fail on drift
        run: |
          python scripts/check_metrics_threshold.py metrics.json
