name: Nightly Tests

permissions:
  contents: read
  issues: write

on:
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run integration tests
        run: |
          python -m pytest -m integration --maxfail=1 --disable-warnings -q || [ $? -eq 5 ]

