name: Perf & Smoke

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1-5"   # weekdays 08:00 UTC

concurrency:
  group: perf-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Import smoke (fail-fast on missing prod deps)
        run: |
          python - <<'PY'
          import importlib
          for m in [
              "ai_trading",
              "ai_trading.core.bot_engine",
              "ai_trading.risk.engine",
              "ai_trading.execution.engine",
          ]:
              importlib.import_module(m)
          print("OK: imports succeeded")
          PY
