name: Preflight

on:
  workflow_dispatch:
  workflow_call:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets
        env:
          DROPLET_HOST: ${{ secrets.DROPLET_HOST }}
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          for var in DROPLET_HOST DROPLET_SSH_KEY DOCKER_REGISTRY DOCKER_USERNAME DOCKER_PASSWORD; do
            if [ -z "${!var}" ]; then
              echo "::error::Missing required secret $var"
              exit 1
            fi
          done
