name: Python CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.2.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu
          pip install pydantic-settings>=0.1.0 pydantic>=2.0 python-dateutil>=2.9.2
          pip install -r requirements.txt
    - name: Run tests with coverage
      run: |
        pip install pytest pytest-cov
        pytest --cov=.
