name: On-Demand Refactor
permissions:
  contents: write
  pull-requests: write

on:
  issue_comment:
    types: [created]

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  refactor:
    if: ${{ contains(github.event.comment.body, '/refactor') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ensure gh CLI
        run: |
          if ! command -v gh > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gh
          fi
      - name: Fetch PR branch
        run: gh pr checkout ${{ github.event.issue.number }}
      - name: Run Codex Refactor
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python scripts/codex_refactor.py --diff "$(git diff main)"
      - uses: EndBug/add-and-commit@v9
        with:
          message: "refactor: apply Codex suggestions"
      - name: Push changes
        run: git push origin HEAD:codex-refactor-${{ github.event.issue.number }}
