name: Draft Release Notes

permissions:
  contents: write
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate release notes
        id: generate_notes
        run: |
          # replace with your notes generator
          echo "::set-output name=notes::$(python scripts/generate_release_notes.py)"
      - name: Post release notes
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Release Notes
            ${{ steps.generate_notes.outputs.notes }}
