name: Draft Release Notes
permissions:
  contents: read
  issues: write

on:
  release:
    types:
      - published

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  draft-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate release notes
        id: gen
        run: |
          notes=$(python scripts/generate_release_notes.py)
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$notes" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Post release notes
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.release.id }}
          body: |
            ## Release Notes
            ${{ steps.gen.outputs.notes }}
