name: Draft Release Notes
on:
  release:
    types: [published]
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update CHANGELOG.md
        run: |
          echo "## Release ${{ github.event.release.tag_name }}" >> CHANGELOG.md
          echo "Changelog drafted" >> CHANGELOG.md
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "actions@github.com"
          message: "chore: update CHANGELOG for ${{ github.event.release.tag_name }}"
