name: Draft Release Notes
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Post release notes
        uses: some/release-notes-action@v1
        with:
          pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: Automated release notes
