name: Draft Release Notes
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate notes
        id: gen
        run: echo "::set-output name=notes::$(python scripts/generate_release_notes.py)"
      - name: Post release notes
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: |
            ## Release Notes
            ${{ steps.gen.outputs.notes }}
