name: Draft Release Notes

permissions:
  contents: write
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  draft-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate release notes
        id: generate_notes
        run: |
          # replace with your notes generator
          echo "::set-output name=notes::$(python scripts/generate_release_notes.py)"
      - name: Post release notes
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Release Notes
            <!-- TODO: fill in summary of changes -->
