name: Security Scan
on:
  push:
    branches: [ main ]
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Trivy
        run: sudo apt-get update && sudo apt-get install -y trivy
      - name: Run Trivy scan
        run: trivy fs --exit-code 1 --severity HIGH,CRITICAL .
