name: Security Scan
on:
  push:
    branches: [ main ]
jobs:
  trivy-scan:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            us-east-1

      - name: Run Trivy security scan
        uses: aquasecurity/trivy-action@v0.23.1
        with:
          image-ref: ubuntu:20.04
