name: Security Scan
on:
  push:
    branches: [ main ]
jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@v0.31.0
        with:
          scan-type: fs
          exit-code: 1
          severity: CRITICAL,HIGH
