name: Notify Slack on Failure

on:
  workflow_run:
    workflows:
      - CI
      - Droplet CI & Nightly Health-Check
      - Test
      - Coverage
      - Nightly Tests
      - Security Scan
      - Model Performance Monitor
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            { "text": ":x: Workflow `${{ github.event.workflow_run.name }}` failed (<${{ github.event.workflow_run.html_url }}|details>)" }

