name: Notify Slack on Failure

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  notify-on-failure:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {"text": ":x: Lint or tests failed on `${{ github.workflow }}` (`${{ github.ref }}`). See <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|details>."}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
