name: Notify Slack on Failure

on:
  workflow_run:
    workflows:
      - CI
      - Droplet CI & Nightly Health-Check
      - Test
      - Coverage
      - Nightly Tests
      - Security Scan
      - Model Performance Monitor
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: ./.github/actions/slack-notify
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: ":x: Workflow `${{ github.event.workflow_run.name }}` failed (<${{ github.event.workflow_run.html_url }}|details>)"

