name: Notify Slack on Failure

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  notify-on-failure:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Notify Slack
        uses: ./.github/actions/slack-notify
        with:
          payload: |
            { "text": ":x: CI failed for ${{ github.workflow }} – ${{ github.run_number }}" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
