name: Notify Slack on Failure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  notify:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            { "text": ":x: CI failed on `${{ github.workflow }}`" }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

