name: Notify Slack on Failure

permissions:
  contents: read

on:
  workflow_run:
    workflows:
      - Droplet CI & Nightly Health-Check
      - Daily Backup
    types:
      - completed

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: slackapi/slack-github-action@v2
        with:
          method: webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: >
            :x: Job *${{ github.event.workflow_run.workflow_name }}* failed.
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}|View run>
