name: Notify Slack on Failure
permissions:
  contents: read
  issues: write

on:
  workflow_run:
    workflows:
      - Droplet CI & Nightly Health-Check
      - Daily Backup
      - Publish Docs
      - On-Demand Refactor
      - Draft Release Notes
    types:
      - completed

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/slack-notify
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: |
            :x: *${{ github.event.workflow_run.workflow_name }}* failed.
            <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}|View run>
