name: Notify Slack on Failure

on:
  workflow_run:
    workflows:
      - CI
      - Droplet CI & Nightly Health-Check
      - Test
      - Coverage
      - Nightly Tests
      - Security Scan
      - Model Performance Monitor
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: ${{ secrets.SLACK_CHANNEL }}
          text: ":x: `${{ github.workflow }}` failed: <${{ github.event.workflow_run.html_url }}|view>"
