name: SSH & Run Tests

on:
  push:
    branches:
      - main

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: SSH to server and run tests
      run: |
        wget https://github.com/appleboy/drone-ssh/releases/download/v1.8.1/drone-ssh-1.8.1-linux-amd64 -O drone-ssh
        chmod +x drone-ssh
        ./drone-ssh --host "$SSH_HOST" --username "$SSH_USER" --password "$SSH_PASSWORD" --command "your-test-command-here"
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
