name: SSH & Run Tests

permissions:
  contents: read
  issues: write

on:
  push:
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt -r requirements-dev.txt
    - name: Run tests
      run: python -m pytest --maxfail=1 --disable-warnings -q
